(function(r,f,m){"use strict";const{sendBotMessage:a}=f.findByProps("sendBotMessage"),y="https://discord.com/channels/1015931589865246730/1092643779523121262";async function w(b,o){try{let e=function(n){return`> ${n.replaceAll(`
`,`
> `)}`},g=function(n){return n.replace(/\[(.*?)\]/g,(M,t)=>(t=t.trim(),`[${t}](<https://www.urbandictionary.com/define.php?term=${encodeURIComponent(t)}> "Definition for \u201C${t}\u201D")`))};const s=new Map(b.map(n=>[n.name,n])),p=s.get("word").value.trim(),k=`https://api.urbandictionary.com/v0/define?term=${encodeURIComponent(p)}`,d=await fetch(k),v=await d.json(),_=s.get("inline_links")?.value||!1,l=v.list?.[0],u=l?.definition;if(!u)return a(o.channel.id,`No definition found for \`${p.replaceAll("`","`\u{E0134}")}\`${d.status!==200?` (${d.status})`:""}`);const h=l.permalink;let i=`__Definition for **\`${l.word}\`**__`;if(_?i+=` ([source](${h} "Link to the place where the definition was found"))
${e(g(u))}`:i+=`
${e(u)}

Source: <${h}>`,s.get("ephemeral")?.value===!1)return{content:i};a(o.channel.id,i)}catch(e){alert(e.stack),console.error(e),a(o.channel.id,`\`\`\`js
${e.stack}\`\`\`An error has occurred while processing the </urban:0> command
Send the error in ${y}, to get this issue solved (hopefully)`)}}let c;var $={onLoad:()=>{c=m.registerCommand({name:"urban",displayName:"urban",description:"Search urban dictionary",displayDescription:"Search urban dictionary",options:[{name:"word",displayName:"word",description:"The word you want the definition for",displayDescription:"The word you want the definition for",required:!0,type:3},{name:"ephemeral",displayName:"ephemeral",description:"Make outputs only be seen by you (default: true)",displayDescription:"Make outputs only be seen by you (default: true)",type:5,required:!1},{name:"inline_links",displayName:"inline_links",description:"Makes the [highlighted] words pressable (default: false)",displayDescription:"Makes the [highlighted] words pressable (default: false)",type:5,required:!1}],execute:w,applicationId:-1,inputType:1,type:1})},onUnload:()=>{c()}};return r.default=$,Object.defineProperty(r,"__esModule",{value:!0}),r})({},vendetta.metro,vendetta.commands);
