(function(r,m,f){"use strict";const{sendBotMessage:o}=m.findByProps("sendBotMessage"),y="https://discord.com/channels/1015931589865246730/1092643779523121262";function w(t){const i="https://www.urbandictionary.com/define.php?term=";return t.replace(/\[(.*?)\]/g,(e,n)=>(n=n.trim(),`[${n}](<${encodeURIComponent(i+n)}>)`))}function c(t){return`> ${t.replaceAll(`
`,`
> `)}`}async function b(t,i){try{const e=new Map(t.map(h=>[h.name,h])),n=e.get("word").value.trim(),g=encodeURIComponent(n),k=`https://api.urbandictionary.com/v0/define?term=${g}`,s=await fetch(k),_=await s.json(),v=e.get("inline_links")?.value||!1,d=_.list?.[0],l=d?.definition;if(!l)return o(i.channel.id,`No definition found for \`${n.replaceAll("`","`\u{E0134}")}\`${s.status!==200?` (${s.status})`:""}`);const p=d.permalink;let a=`__Definition for **\`${d.word}\`**__`;if(v?a+=` ([source](${p}))
${c(w(l))}`:a+=`
${c(l)}

Source: <${p}>`,e.get("ephemeral")?.value===!1)return{content:a};o(i.channel.id,a)}catch(e){alert(e.stack),console.error(e),o(i.channel.id,`\`\`\`js
${e.stack}\`\`\`An error has occurred while processing the </urban:0> command
Send the error in ${y}.`)}}let u;var $={onLoad:()=>{u=f.registerCommand({name:"urban",displayName:"urban",description:"Search urban dictionary",displayDescription:"Search urban dictionary",options:[{name:"word",displayName:"word",description:"The word you want the definition for",displayDescription:"The word you want the definition for",required:!0,type:3},{name:"ephemeral",displayName:"ephemeral",description:"Make outputs only be seen by you (default: true)",displayDescription:"Make outputs only be seen by you (default: true)",type:5,required:!1},{name:"inline_links",displayName:"inline_links",description:"Makes the [highlighted] words pressable (default: false)",displayDescription:"Makes the [highlighted] words pressable (default: false)",type:5,required:!1}],execute:b,applicationId:-1,inputType:1,type:1})},onUnload:()=>{u()}};return r.default=$,Object.defineProperty(r,"__esModule",{value:!0}),r})({},vendetta.metro,vendetta.commands);
